export const tokens = {
  color: {
    light: {
      background: "#F5F3FF",
      foreground: "#1E1B2E",
      card: "#FFFFFF",
      "card-foreground": "#1E1B2E",
      popover: "#FFFFFF",
      "popover-foreground": "#1E1B2E",
      primary: "#7C3AED",
      "primary-foreground": "#FFFFFF",
      secondary: "#EDE9FE",
      "secondary-foreground": "#1E1B2E",
      muted: "#C4B5FD",
      "muted-foreground": "#4C4469",
      accent: "#1E1B2E",
      "accent-foreground": "#FFFFFF",
      destructive: "#EF4444",
      border: "#DDD6FE",
      input: "#DDD6FE",
      ring: "#7C3AED",
    },
    dark: {
      background: "#0F0A1E",
      foreground: "#EDE9FE",
      card: "#1A1033",
      "card-foreground": "#EDE9FE",
      popover: "#1A1033",
      "popover-foreground": "#EDE9FE",
      primary: "#9D5FF3",
      "primary-foreground": "#0F0A1E",
      secondary: "#1A1033",
      "secondary-foreground": "#EDE9FE",
      muted: "#3D2F6B",
      "muted-foreground": "#D8CDE0",
      accent: "#F5F3FF",
      "accent-foreground": "#0F0A1E",
      destructive: "#F87171",
      border: "#3D2F6B",
      input: "#3D2F6B",
      ring: "#9D5FF3",
    },
  },
  spacing: {
    "0": "0",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px",
    "20": "80px",
    "24": "96px",
    "32": "128px",
  },
  borderRadius: {
    none: "0",
    sm: "6px",
    base: "10px",
    md: "10px",
    lg: "14px",
    xl: "16px",
    "2xl": "20px",
    "3xl": "24px",
    "4xl": "28px",
    full: "9999px",
  },
  fontFamily: {
    heading: "Fraunces",
    body: "Source Serif 4",
    sans: "system-ui, -apple-system, sans-serif",
    mono: "JetBrains Mono",
  },
} as const;

export type ColorToken = (typeof tokens.color.light)[keyof typeof tokens.color.light];
export type SpacingToken = (typeof tokens.spacing)[keyof typeof tokens.spacing];
export type BorderRadiusToken = (typeof tokens.borderRadius)[keyof typeof tokens.borderRadius];
export type FontFamilyToken = (typeof tokens.fontFamily)[keyof typeof tokens.fontFamily];